# Generated by Django 3.2.3 on 2021-07-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.FileField(max_length=1000, upload_to='static/images/%Y/%m/%d/')),
            ],
        ),
    ]
