# Generated by Django 3.2.4 on 2021-07-01 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_details', serialize=False, to='auth.user')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('about', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.CharField(blank=True, max_length=2000, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('city_longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('city_latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('address_longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('address_latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
