# Generated by Django 3.2.4 on 2021-07-07 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210701_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.company'),
        ),
    ]
