# Generated by Django 3.2.9 on 2021-11-16 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20211115_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userteam',
            name='user_status',
        ),
        migrations.CreateModel(
            name='RequestTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('pending', 'в ожидании'), ('accepted', 'принято'), ('canceled', 'отменено'), ('rejected', 'отклоненный')], max_length=255, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_request', to='user.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
