# Generated by Django 3.2.4 on 2021-07-08 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_userdetail_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Organization',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='company',
            new_name='organization',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
