# Generated by Django 3.2.9 on 2021-11-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211116_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestteam',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'в ожидании'), ('accepted', 'принято'), ('canceled', 'отменено'), ('rejected', 'отклоненный')], default='pending', max_length=255, null=True),
        ),
    ]
