# Generated by Django 3.2.4 on 2021-07-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210708_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='admin',
            new_name='org_leader',
        ),
    ]
