# Generated by Django 3.2.9 on 2021-11-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_requestteam_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoverEmail',
            fields=[
                ('token', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
