# Generated by Django 3.2.9 on 2021-12-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_recoveremail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
