# Generated by Django 3.2.4 on 2021-07-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_confirmcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
