# Generated by Django 3.2.4 on 2021-07-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userdetail_is_removed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='organization',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='user.Organization'),
        ),
    ]
