# Generated by Django 3.2.4 on 2021-07-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210723_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='is_removed',
        ),
    ]
