# Generated by Django 3.2.4 on 2021-07-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_userdetail_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
