# Generated by Django 3.2.4 on 2021-08-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20210803_1038'),
        ('user', '0010_organization_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='fave_foods',
            field=models.ManyToManyField(blank=True, to='food.Food'),
        ),
    ]
