# Generated by Django 3.2.6 on 2021-11-01 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmcode',
            name='phone_number',
        ),
    ]
