# Generated by Django 3.2.9 on 2021-12-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_slide_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=1000, null=True)),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
