# Generated by Django 3.2.4 on 2021-08-03 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_plate_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platelayout',
            name='entree_count',
        ),
        migrations.AddField(
            model_name='plate',
            name='foods',
            field=models.ManyToManyField(to='food.Food'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='platelayout',
            name='has_dessert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platelayout',
            name='has_drink',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PlateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.foodcategory')),
            ],
        ),
        migrations.AddField(
            model_name='platelayout',
            name='sections',
            field=models.ManyToManyField(blank=True, to='food.PlateSection'),
        ),
    ]
