# Generated by Django 3.2.9 on 2021-12-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_subscribe_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='has_dessert',
        ),
        migrations.RemoveField(
            model_name='box',
            name='has_drink',
        ),
        migrations.RemoveField(
            model_name='box',
            name='user',
        ),
        migrations.AddField(
            model_name='box',
            name='foods',
            field=models.ManyToManyField(blank=True, related_name='box_food', to='food.Food'),
        ),
        migrations.AddField(
            model_name='box',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
