# Generated by Django 3.2.9 on 2021-12-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_images_timeinterval'),
        ('food', '0003_auto_20211215_0718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeInterval',
        ),
        migrations.RemoveField(
            model_name='box',
            name='images',
        ),
        migrations.AddField(
            model_name='box',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='box_images', to='utils.Images'),
        ),
    ]
