# Generated by Django 3.2.4 on 2021-08-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20210803_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='foods',
            field=models.ManyToManyField(blank=True, to='food.Food'),
        ),
    ]
