# Generated by Django 3.2.6 on 2021-08-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20210826_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='food',
            field=models.ManyToManyField(blank=True, related_name='food_ingridients', to='food.Food'),
        ),
    ]
