# Generated by Django 3.2.6 on 2021-08-31 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_auto_20210831_1044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drink',
        ),
    ]
