# Generated by Django 3.2.6 on 2021-09-06 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_delete_drink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='foods',
        ),
        migrations.AddField(
            model_name='plate',
            name='dessert',
            field=models.ManyToManyField(blank=True, related_name='food_dessert', to='food.Food'),
        ),
        migrations.AddField(
            model_name='plate',
            name='drink',
            field=models.ManyToManyField(blank=True, related_name='food_drink', to='food.Food'),
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_count', models.IntegerField(default=0)),
                ('day', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_plate', to='food.plate')),
            ],
        ),
        migrations.CreateModel(
            name='SectionFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='food.food')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='food.platesection')),
            ],
        ),
        migrations.AddField(
            model_name='plate',
            name='section_food',
            field=models.ManyToManyField(blank=True, to='food.SectionFood'),
        ),
    ]
