# Generated by Django 3.2.6 on 2021-09-06 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_plate_foods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionfood',
            old_name='section',
            new_name='sections',
        ),
    ]
