# Generated by Django 3.2.6 on 2021-09-08 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0018_remove_plate_foods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('has_drink', models.BooleanField(default=False)),
                ('has_dessert', models.BooleanField(default=False)),
                ('dessert', models.ManyToManyField(blank=True, related_name='box_dessert', to='food.Food')),
                ('drink', models.ManyToManyField(blank=True, related_name='box_drink', to='food.Food')),
                ('layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layout_box', to='food.platelayout')),
                ('section_food', models.ManyToManyField(blank=True, to='food.SectionFood')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
