# Generated by Django 3.2.6 on 2021-09-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='address_latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='address_longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='has_dessert',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='has_drink',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='section_food',
            field=models.ManyToManyField(blank=True, related_name='plate_section_food', to='food.SectionFood'),
        ),
    ]
