# Generated by Django 3.2.6 on 2021-09-13 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0020_auto_20210910_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='dessert',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='has_dessert',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='has_drink',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='section_food',
        ),
        migrations.CreateModel(
            name='PlateSectionFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_food_plate', to='food.plate')),
                ('section_food', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='plate_section_food', to='food.sectionfood')),
            ],
        ),
        migrations.CreateModel(
            name='PlateDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('drink', models.ManyToManyField(blank=True, related_name='food_drink', to='food.Food')),
                ('plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plate_drink', to='food.plate')),
            ],
        ),
        migrations.CreateModel(
            name='PlateDessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('dessert', models.ManyToManyField(blank=True, related_name='food_dessert', to='food.Food')),
                ('plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plate_dessert', to='food.plate')),
            ],
        ),
    ]
