# Generated by Django 3.2.6 on 2021-09-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_auto_20210913_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platedrink',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='platedrink',
            name='plate',
        ),
        migrations.RemoveField(
            model_name='platesectionfood',
            name='plate',
        ),
        migrations.RemoveField(
            model_name='platesectionfood',
            name='section_food',
        ),
        migrations.AddField(
            model_name='plate',
            name='dessert',
            field=models.ManyToManyField(blank=True, related_name='food_dessert', to='food.Food'),
        ),
        migrations.AddField(
            model_name='plate',
            name='drink',
            field=models.ManyToManyField(blank=True, related_name='food_drink', to='food.Food'),
        ),
        migrations.AddField(
            model_name='plate',
            name='section_food',
            field=models.ManyToManyField(blank=True, related_name='plate_section_food', to='food.SectionFood'),
        ),
        migrations.DeleteModel(
            name='PlateDessert',
        ),
        migrations.DeleteModel(
            name='PlateDrink',
        ),
        migrations.DeleteModel(
            name='PlateSectionFood',
        ),
    ]
