# Generated by Django 3.2.6 on 2021-09-14 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0022_auto_20210913_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='drink',
        ),
        migrations.AlterField(
            model_name='box',
            name='has_dessert',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='has_drink',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PlateDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_count', models.FloatField()),
                ('drink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plate_drink', to='food.food')),
                ('plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drink_plate', to='food.plate')),
            ],
        ),
    ]
