# Generated by Django 3.2.6 on 2021-09-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0023_auto_20210914_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platedrink',
            name='drink_count',
            field=models.IntegerField(default=0),
        ),
    ]
