# Generated by Django 3.2.6 on 2021-09-14 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0024_alter_platedrink_drink_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionfood',
            name='sections',
        ),
        migrations.AddField(
            model_name='sectionfood',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='food.platesection'),
        ),
        migrations.RemoveField(
            model_name='platedrink',
            name='drink',
        ),
        migrations.AddField(
            model_name='platedrink',
            name='drink',
            field=models.ManyToManyField(blank=True, null=True, related_name='plate_drink', to='food.Food'),
        ),
    ]
