# Generated by Django 3.2.6 on 2021-09-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0025_auto_20210914_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platedrink',
            old_name='drink_count',
            new_name='count',
        ),
        migrations.AlterField(
            model_name='platedrink',
            name='drink',
            field=models.ManyToManyField(blank=True, related_name='plate_drink', to='food.Food'),
        ),
    ]
