# Generated by Django 3.2.6 on 2021-09-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0026_auto_20210914_0737'),
    ]

    operations = [

        migrations.AlterField(
            model_name='box',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plate',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='platelayout',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='platelayout',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='platesection',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='platesection',
            name='name',
            field=models.TextField(),
        ),
    ]
