# Generated by Django 3.2.6 on 2021-09-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0027_auto_20210924_0729'),
    ]

    operations = [

    ]
