# Generated by Django 3.2.6 on 2021-09-27 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0029_auto_20210925_0810'),
    ]

    operations = [

        migrations.CreateModel(
            name='PlateDessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('dessert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plate_dessert', to='food.food')),
            ],
        ),
        migrations.AlterField(
            model_name='plate',
            name='dessert',
            field=models.ManyToManyField(blank=True, related_name='food_dessert', to='food.PlateDessert'),
        ),
    ]
