# Generated by Django 3.2.6 on 2021-09-27 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0030_auto_20210927_0611'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='plate',
            name='dessert',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='drink',
        ),
        migrations.AddField(
            model_name='platedessert',
            name='plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dessert_plate', to='food.plate'),
        ),
        migrations.AddField(
            model_name='platedrink',
            name='plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drink_plate', to='food.plate'),
        ),
    ]
