# Generated by Django 3.2.6 on 2021-09-27 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0031_auto_20210927_0643'),
    ]

    operations = [
              migrations.RemoveField(
            model_name='plate',
            name='section_food',
        ),
        migrations.CreateModel(
            name='PlateSectionFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_food_plate', to='food.plate')),
                ('section_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plate_section_food', to='food.sectionfood')),
            ],
        ),
    ]
