# Generated by Django 3.2.6 on 2021-09-27 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0032_auto_20210927_0804'),
    ]

    operations = [

    ]
