# Generated by Django 3.2.6 on 2021-10-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0033_auto_20210927_0805'),
    ]

    operations = [

        migrations.AddField(
            model_name='subscribe',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
