# Generated by Django 3.2.6 on 2021-10-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0034_auto_20211001_0651'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='plate',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='day',
        ),
        migrations.AddField(
            model_name='plate',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
