# Generated by Django 3.2.6 on 2021-10-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0035_auto_20211001_0808'),
    ]

    operations = [

    ]
