# Generated by Django 3.2.6 on 2021-10-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0037_auto_20211005_0715'),
    ]

    operations = [

    ]
