# Generated by Django 3.2.6 on 2021-10-06 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0038_auto_20211005_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SectionLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='sectionfood',
            name='food',
        ),
        migrations.RemoveField(
            model_name='sectionfood',
            name='section',
        ),
        migrations.RemoveField(
            model_name='box',
            name='section_food',
        ),
        migrations.RemoveField(
            model_name='platelayout',
            name='sections',
        ),
        migrations.DeleteModel(
            name='PlateSectionFood',
        ),
        migrations.DeleteModel(
            name='SectionFood',
        ),
        migrations.AddField(
            model_name='sectionlayout',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='food.platelayout'),
        ),
        migrations.AddField(
            model_name='sectionlayout',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='food.platesection'),
        ),
        migrations.AddField(
            model_name='platefood',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plate_food', to='food.food'),
        ),
        migrations.AddField(
            model_name='platefood',
            name='plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_plate', to='food.plate'),
        ),
        migrations.AddField(
            model_name='platefood',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_plate_food', to='food.sectionlayout'),
        ),
    ]
