# Generated by Django 3.2.6 on 2021-10-07 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0039_auto_20211006_0559'),
    ]

    operations = [
              migrations.RemoveField(
            model_name='platefood',
            name='section',
        ),
        migrations.AddField(
            model_name='platefood',
            name='section_layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_layout_plate_food', to='food.sectionlayout'),
        ),
    ]
