# Generated by Django 3.2.6 on 2021-10-08 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0040_auto_20211007_0639'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='subscribe',
            name='price',
        ),
        migrations.AddField(
            model_name='plate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
