# Generated by Django 3.2.6 on 2021-10-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0042_auto_20211008_0817'),
    ]

    operations = [
                migrations.AddField(
            model_name='subscribe',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='plate',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='plate',
            field=models.ManyToManyField(related_name='subscribe_plate', to='food.Plate'),
        ),
    ]
