# Generated by Django 3.2.6 on 2021-10-15 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0043_auto_20211012_0546'),
    ]

    operations = [

        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('payment_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=255, null=True)),
                ('refunded_amount', models.FloatField(blank=True, default=0, null=True)),
                ('refunded_date', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_transactions', to=settings.AUTH_USER_MODEL)),
                ('subscribe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacion_subscribe', to='food.subscribe')),
            ],
        ),
    ]
