# Generated by Django 3.2.6 on 2021-10-18 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0044_auto_20211015_0737'),
    ]

    operations = [

        migrations.CreateModel(
            name='RequestToCancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('new', 'новый'), ('pending', 'в ожидании'), ('cancel', 'отменить'), ('approved', 'утверждена')], default='new', max_length=255, null=True)),
                ('subscribe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_subscribe', to='food.subscribe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
