# Generated by Django 3.2.6 on 2021-10-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0046_auto_20211019_0717'),
    ]

    operations = [

    ]
