# Generated by Django 3.2.6 on 2021-10-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0047_auto_20211027_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),

    ]
