# Generated by Django 3.2.6 on 2021-10-29 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0048_auto_20211028_0659'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='take',
            name='section',
        ),
        migrations.AddField(
            model_name='take',
            name='section_layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='take_section', to='food.sectionlayout'),
        ),
        migrations.AlterField(
            model_name='sectionlayout',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layout_section', to='food.platelayout'),
        ),
        migrations.AlterField(
            model_name='sectionlayout',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_layout', to='food.platesection'),
        ),
    ]
