# Generated by Django 3.2.6 on 2021-11-01 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0049_auto_20211029_0740'),
    ]

    operations = [

    ]
